plugins {
    id 'com.android.application'
}

android {
    namespace 'com.enabcd.navigation'
    compileSdk 35

    defaultConfig {
        applicationId 'com.enabcd.navigation'
        minSdk 23
        targetSdk 35
        versionCode 8
        versionName '1.7.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.12.1'
}
